language: node_js
node_js:
- '6'
before_install:
- rvm install 2.2.2
install: gem install jekyll html-proofer
before_script:
- npm install
script:
- npm run build
notifications:
  slack:
    secure: n0KSSChpOGhLOm40BV2dbUr7XoITStPVgDL/eOsvAGA13Nj17tSjbAGmTFjHwaT/yYjfOX4osiZeQ6g0PKuoEpiMq2myod9c8EV5Xobb7eCw+x1yJ5d2F6tqx/kjcsmnLXfUIIL7pTOVtBc1QzkZmWWZWZGBNHrSJ9IPECsfc8QJ3ChQ0+XU5hnfj7BmKkHYiKNarEJLGH/DCK9kr5VzRhynI+itEpCCzgk5FQcMH7RQyItHGVHnS1BuHc9fhyMKJ2BBAJQr6qC024Yvm/BLCn//ICz4yExsoA4HsdjlIvUtum51q//kmiPyTf1a7IjIMV2YTAxEoGqwJOrsT94zBKRdPSDiTrLuwsZM4VNHiOHtl+A7v6Dw3sAlguzRZQFJNXV0SWfqhsDgvGgBjfQ6MNTIFKbgih0m/x2AQNwsGGCU0YIk8OAfIO+/0X6sjouXRIvtXGGFoDoqXCnGnb6kujzpE9xRZttTUcWz7vYCYtEWg1G98xdGjcifEhKgbtjiYii5QtSK/8nlbX4PVV2O2S0ZxatwavCstZL0iBlajif3OAx3HW0gtoa9GJ0zgfrZS69RDbHbrsTxgge057WMx0l63tn1sgAGGCFf4vHQSdsn7IhVD8H89qAMFoNCXmZ9yCf7MeuWJsMNZ6hv1bw93ZTiDeQT3A3kn7Cwhl8dv5c=
