language: ruby
rvm:
- 2.1
install: gem install jekyll html-proofer
before_script:
- npm install
script:
- npm run build
notifications:
  slack:
    secure: LhqqQAdqPjgHfya5yT8FnNVM/SoQ/Ye7oYPkWLA5AFITRqxqH/N5FGtbhfi+U6PazkKc6X6k77Ei72WlqaGxzpZM43UXHZhwhq9W0M8+C82D/FtC6kD3998U7eqVYATU0kbOxEgH2VKb5vw1BJHt1L/uZ7XN+N9BuvNqtX1M1Ed+LpCibcCBYAypw1175s8Da7CajU4kFpIdgK1Cj7FkN7+tH9krl9c1YCJRS8uEhlDxpt+MHuoNnhv1Ol/YQ89c8ANoIt0HV881QrOk65HOuhyG3nsqKfvrxFwXNN/PGKn+9zKg9k+6uaOk3c2LwLmYGD97ETXEsBitawmyUDiBFxYRRav+bdX11ohOl/vD8YXvk6/ktvnXIuuMaIgBjyWYh98ZoQZIbRkRGuJYtVqmp8CL5zCBTkxyLXHJgeqNDe87R8cPVQwZM+ixQf1q0D5WhO5Cst4OH/cU6XGx7mhq6L/mPVvdtkvgHrav4nlRBkTrR4MFA1LZmHDL0/dIm1YAFwLhSXzFKPFI7pBAra4XHmLlNLhZrVOUT2q1cdJM1ChjnXebw5seE3MMaL9f/BU0xarlPoHAxTQsACwFfQTPTKh2YMZVI3bPgD+E5o3ScfGguBi0fuVUAZQ8dUf3/xJ3wkWX6TSbj3g9MiYa2dKnbBgIJw4PNGemtzWJzmVtPcU=
